spring:
  application:
    name: iwinner-order-realtime-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mif?useSSL=false
    username: root
    password: root
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  data:
    cassandra:
      keyspace-name: iwinner_order_db
      contact-points: 127.0.0.1
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      order_topic: iwinner_order_service_lap_1003
server:
    port: 9000

iwinner_order:
  scheduler:
    status: PROCESS
aws:
  region: us-east-1
  access_key_id: WELCOME
  secret_access_key: WELCOME
  bucket_name: iwinner-order-realtime
